'''
bool(obj)获取指定对象的布尔值
str（obj）将指定对象转换为字符型
int（x）将x转换为int类型
float(x)将x转换为float类型
list(sequence)将序列转换为列表类型
tuple(sequence)将序列转换为元组类型
set(sequence)将序列转换成集合类型
'''
print(bool('hello'))
print(bool(''))
print(bool([]))
print(bool(()))
print(bool(list()))
print(bool(tuple()))
print(bool(set()))
print(bool({}))
print(bool(dict()))
print('_'*50)
print(bool(123))
print(bool(0))
print(bool(0.0))
print('_'*50)
lst=[1,2,3]

print(type(lst),lst)
s=str(lst)
print(type(s),s)