# Generated by Django 5.2.5 on 2025-08-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_data_userinfo_size_alter_userinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
